# Servidor
server.port=8080

# Base de datos H2 en memoria para pruebas directas
spring.datasource.url=jdbc:h2:mem:inventariodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Generación automática de tablas
spring.jpa.hibernate.ddl-auto=update

# Configuración IDaaS (Ejemplo Azure AD / Entra ID)
# Reemplazar con el Issuer URI real de tu tenant cuando se configure en la nube
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/{TENANT_ID}/v2.0