# Servidor
server.port=8080

# Base de datos H2 local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:inventariodb}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.h2.console.enabled=true

# Generación automática de tablas JPA
spring.jpa.hibernate.ddl-auto=update

## Emisor (Domain de Auth0 con barra al final '/')
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-mh13n.us.auth0.com/

# Audiencia (Identifier exacto de tu API en Auth0)
spring.security.oauth2.resourceserver.jwt.audiences=https://stock360-api
# API Gateway y desarrollo local (CORS)
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://stock360-5953a.web.app}

# Indicar a Spring que ejecute data.sql DESPUÉS de que JPA cree las tablas
spring.jpa.defer-datasource-initialization=true
